WITH PAID_SESSIONS AS (
    SELECT
        S.VISITOR_ID,
        S.VISIT_DATE,
        S.SOURCE AS UTM_SOURCE,
        S.MEDIUM AS UTM_MEDIUM,
        S.CAMPAIGN AS UTM_CAMPAIGN,
        ROW_NUMBER() OVER (
            PARTITION BY S.VISITOR_ID
            ORDER BY S.VISIT_DATE DESC
        ) AS RN
    FROM
        SESSIONS AS S
    WHERE
        S.MEDIUM IN ('cpc', 'cpm', 'cpa', 'youtube', 'cpp', 'tg', 'social')
),

LAST_PAID_CLICKS AS (
    SELECT
        VISITOR_ID,
        VISIT_DATE,
        UTM_SOURCE,
        UTM_MEDIUM,
        UTM_CAMPAIGN
    FROM
        PAID_SESSIONS
    WHERE
        RN = 1
)

SELECT
    LPC.VISITOR_ID,
    LPC.VISIT_DATE,
    LPC.UTM_SOURCE,
    LPC.UTM_MEDIUM,
    LPC.UTM_CAMPAIGN,
    L.LEAD_ID,
    L.CREATED_AT,
    L.AMOUNT,
    L.CLOSING_REASON,
    L.STATUS_ID
FROM
    LAST_PAID_CLICKS AS LPC
LEFT JOIN
    LEADS AS L
    ON
        LPC.VISITOR_ID = L.VISITOR_ID
        AND LPC.VISIT_DATE <= L.CREATED_AT
ORDER BY
    L.AMOUNT DESC NULLS LAST,
    LPC.VISIT_DATE ASC,
    LPC.UTM_SOURCE ASC,
    LPC.UTM_MEDIUM ASC,
    LPC.UTM_CAMPAIGN ASC
LIMIT 10;
