WITH PAID_SESSIONS AS (
    SELECT
        S.VISITOR_ID,
        S.VISIT_DATE,
        S.SOURCE AS UTM_SOURCE,
        S.MEDIUM AS UTM_MEDIUM,
        S.CAMPAIGN AS UTM_CAMPAIGN,
        ROW_NUMBER() OVER (
            PARTITION BY S.VISITOR_ID
            ORDER BY S.VISIT_DATE DESC
        ) AS RN
    FROM
        SESSIONS AS S
    WHERE
        S.MEDIUM IN ('cpc', 'cpm', 'cpa', 'youtube', 'cpp', 'tg', 'social')
)

SELECT
    PS.VISITOR_ID,
    PS.VISIT_DATE,
    PS.UTM_SOURCE,
    PS.UTM_MEDIUM,
    PS.UTM_CAMPAIGN,
    L.LEAD_ID,
    L.CREATED_AT,
    L.AMOUNT,
    L.CLOSING_REASON,
    L.STATUS_ID
FROM
    PAID_SESSIONS AS PS
LEFT JOIN
    LEADS AS L
    ON
        PS.VISITOR_ID = L.VISITOR_ID
        AND PS.VISIT_DATE <= L.CREATED_AT
WHERE
    PS.RN = 1
ORDER BY
    L.AMOUNT DESC NULLS LAST,
    PS.VISIT_DATE ASC,
    PS.UTM_SOURCE ASC,
    PS.UTM_MEDIUM ASC,
    PS.UTM_CAMPAIGN ASC
LIMIT 10;

